name: SkyblockX
main: io.illyria.skyblockx.SkyblockX
version: ${project.version}
api-version: '1.13'
load: POSTWORLD
commands:
  skyblockx:
    description: 'base skyblock command'
    aliases: [skyblock, sskyblock, sb, sblock]
  is:
    description: 'base savageskyblock command'
    aliases: [island]

